---
title: "R Notebook"
output: html_notebook
---

# Setup

```{r}
# clear the workspace
rm(list=ls())

library(odbc)
library(tidyverse)

year <- 2015
gasb.archive <- c('f1415_f1a.zip','flags2015.zip')
gasb.infile <- c('f1415_f1a_rv.csv','flags2015.csv')
fasb.archive <- c('f1415_f2.zip','flags2015.zip')
fasb.infile <- c('f1415_f2_rv.csv','flags2015.csv')

odbcString <- "cdw"
urlStub <- "http://nces.ed.gov/ipeds/datacenter/data/"

# access data via net
netLoad <- function(fileUrl, fileName)
{
  #Download data file
  temp <- tempfile()
  
  download.file(fileUrl,
                temp)
  
  data <- read_csv(unz(temp, fileName))
  
  unlink(temp)
  # rm(temp)
  
  names(data) <- tolower(names(data))
  return(data)
}

```

# Load GASB Data From NCES

```{r}
raw.dat <- netLoad(paste0(urlStub, gasb.archive[1]),
                    gasb.infile[1]) %>%
  left_join(netLoad(paste0(urlStub, gasb.archive[2]),
                    gasb.infile[2]), by = 'unitid') %>%
  mutate(Unitid = unitid,
         YearId = year)

raw.dat

```

# Restructure and Create GASB Data Frame

```{r}

gasb <- raw.dat %>%
  gather(f1c012, f1c013, f1c014, f1c015, f1c016, f1c017,
         f1c022, f1c023, f1c024, f1c025, f1c026, f1c027,
         f1c032, f1c033, f1c034, f1c035, f1c036, f1c037,
         f1c052, f1c053, f1c054, f1c055, f1c056, f1c057,
         f1c062, f1c063, f1c064, f1c065, f1c066, f1c067,
         f1c072, f1c073, f1c074, f1c075, f1c076, f1c077,
         f1c082, f1c083, f1c084, f1c085, f1c086, f1c087,
         f1c105,
         f1c112, f1c113, f1c114, f1c115, f1c116, f1c117,
         f1c122, f1c123, f1c124, f1c125, f1c126, f1c127,
         f1c132, f1c133, f1c134, f1c135, f1c136, f1c137,
         f1c142, f1c143, f1c144, f1c145, f1c146, f1c147,
         key = 'field', value = 'Expense') %>%
  mutate(field = substr(field, 4, 6)) %>%
  separate(field, c('FunctionalClassification','NaturalClassification'), 2) %>%
  mutate(FunctionalClassification = recode(FunctionalClassification,
                                             '01'='Instruction',
                                             '02'='Research',
                                             '03'='Public service',
                                             '05'='Academic support',
                                             '06'='Student services',
                                             '07'='Institutional support',
                                             '08'='Operation and maintenance of plant',
                                             '10'='Scholarships and fellowships',
                                             '11'='Auxiliary enterprises',
                                             '12'='Hospital services',
                                             '13'='Independent operations',
                                             '14'='Other',
                                             '15'='Total'),
         NaturalClassification = recode(NaturalClassification,
                                          '1'='Total',
                                          '2'='Salaries and wages',
                                          '3'='Fringe benefits',
                                          '4'='Depreciation',
                                          '5'='Other',
                                          '6'='Operation and maintenance of plant',
                                          '7'='Interest'),
         Expense = ifelse(is.na(Expense),0,Expense)) %>%
  select(Unitid,
         YearId,
         FunctionalClassification,
         NaturalClassification,
         Expense)

rm(raw.data)

gasb
```

# Load FASB Data From NCES

```{r}
raw.dat <- netLoad(paste0(urlStub, fasb.archive[1]),
                   fasb.infile[1]) %>%
  left_join(netLoad(paste0(urlStub, fasb.archive[2]),
                    fasb.infile[2]), by = 'unitid') %>%
  mutate(Unitid = unitid,
         YearId = year)

raw.data
```

# Restructure and Create GASB Data Frame

```{r}
expenses <- raw.dat %>%
  gather(f2e012, f2e013, f2e014, f2e015, f2e016, f2e017,
         f2e022, f2e023, f2e024, f2e025, f2e026, f2e027,
         f2e032, f2e033, f2e034, f2e035, f2e036, f2e037,
         f2e042, f2e043, f2e044, f2e045, f2e046, f2e047,
         f2e052, f2e053, f2e054, f2e055, f2e056, f2e057,
         f2e062, f2e063, f2e064, f2e065, f2e066, f2e067,
         f2e072, f2e073, f2e074, f2e075, f2e076, f2e077,
         f2e087,
         f2e092, f2e093, f2e094, f2e095, f2e096, f2e097,
         f2e102, f2e103, f2e104, f2e105, f2e106, f2e107,
         f2e112, f2e113, f2e114, f2e115, f2e116, f2e117,
         f2e122, f2e123, f2e124, f2e125, f2e126, f2e127,
         key = 'field', value = 'Expense') %>%
  mutate(field = substr(field, 4, 6)) %>%
  separate(field, c('FunctionalClassification','NaturalClassification'), 2) %>%
  mutate(FunctionalClassification = recode(FunctionalClassification,
                                           '01'='Instruction',
                                           '02'='Research',
                                           '03'='Public service',
                                           '04'='Academic support',
                                           '05'='Student services',
                                           '06'='Institutional support',
                                           '07'='Auxiliary enterprises',
                                           '08'='Net grant aid to students',
                                           '09'='Hospital services',
                                           '10'='Independent operations',
                                           '11'='Operation and maintenance of plant',
                                           '12'='Other',
                                           '13'='Total'),
         NaturalClassification = recode(NaturalClassification,
                                        '1'='Total',
                                        '2'='Salaries and wages',
                                        '3'='Fringe benefits',
                                        '5'='Depreciation',
                                        '7'='Other',
                                        '4'='Operation and maintenance of plant',
                                        '6'='Interest'),
         Expense = ifelse(is.na(Expense),0,Expense)) %>%
  select(Unitid,
         YearId,
         FunctionalClassification,
         NaturalClassification,
         Expense)

```

# Load Database

```{r}
con <- dbConnect(odbc::odbc(), odbcString)

# response <- dbSendQuery(con, paste0('DELETE FROM dbo.IpedsExpenses WHERE YearId=', year))
# dbClearResult(response)

system.time({ dbWriteTable(con, 'IpedsExpenses', expenses, append=TRUE) })

dbDisconnect(con)

```

