---
title: "Check Fall Staff Notebook"
date: 2018-12-18
output: html_notebook
params:
  year:
    label: "Year (Fall)"
    value: 2017
---

# Setup

```{r setup}
# knitr options
knitr::opts_chunk$set(fig.width = 8,
                      fig.asp = 0.618,
                      echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

library(DBI)
library(odbc)
library(readxl)
library(lubridate)
library(kableExtra)
library(tidyverse)

# access zipped data via net
net_load_zip <- function(file_url, file_name)
{
  #Download data file
  temp <- tempfile()
  
  download.file(file_url,
                temp)
  
  files <- unzip(temp, list = TRUE)

  spec <- files$Name[str_detect(files$Name, "_rv")]

  file_name <- ifelse(length(spec) == 0, file_name, spec)
  
  data <- read_csv(unz(temp, file_name),
                   locale = locale(encoding = "latin1")) %>%
    rename_all(tolower)
  
  unlink(temp)
  rm(temp)
  
  return(data)
}

read_file <- function(url, file) {
  df <- net_load_zip(url, file)
  
  drop_fields <- df %>%
    select(starts_with("x")) %>%
    colnames(.)

df %>%
  select(-drop_fields)

}

occupational_category <- read_file(str_c("https://nces.ed.gov/ipeds/datacenter/data/s", params$year, "_oc.zip"),
                                   str_c("s", params$year, "_oc.csv")) %>%
  mutate(unitid = as.integer(unitid),
         facstat = ifelse(occupcat > 399, 60, 90),
         facstat = ifelse(staffcat == 3210, 49, facstat),
         facstat = ifelse(ftpt == 4, 55, facstat),
         occupcat = ifelse(occupcat == 210,
                           211,
                           as.integer(occupcat)),
         faculty_rank = "Unknown",
         source = "staff",
         time_status = recode(ftpt,
                              `2` = "Full-time",
                              .default = "Part-time")) %>%
  filter(ftpt > 1,
         staffcat %in% c(2220, 2230, 2261, 2262, 2263, 2264, 2270,
                         2300, 2310, 2320, 2330, 2340, 2350, 2360, 2370, 2380, 2390,
                         3210, 3220, 3230, 3261, 3262, 3263, 3264, 3270, 
                         3310, 3320, 3330, 3340, 3350, 3360, 3370, 3380, 3390,
                         4410, 4420, 4430, 4440, 4450, 4460, 4470, 4480)) %>%
  select(unitid, source, occupcat, facstat, faculty_rank, time_status,
         hrnralm, hrnralw, hrunknm, hrunknw, hrhispm, hrhispw,
         hraianm, hraianw, hrasiam, hrasiaw, hrbkaam, hrbkaaw,
         hrnhpim, hrnhpiw, hrwhitm, hrwhitw, hr2morm, hr2morw)

instructional_staff <- read_file(str_c("https://nces.ed.gov/ipeds/datacenter/data/s", params$year, "_is.zip"),
                                 str_c("s", params$year, "_is.csv")) %>%
  mutate(unitid = as.integer(unitid),
         factstat = ifelse(facstat %in% c(20, 30, 41, 42, 43, 44, 45, 50, 60), as.integer(facstat), 0),
         occupcat = ifelse(facstat %in% c(20, 30),
                           215,
                           211),
         time_status = "Full-time",
         faculty_rank = recode(arank,
                               `1` = "Professors",
                               `2` = "Associate Professors",
                               `3` = "Assistant Professors",
                               `4` = "Instructors",
                               `5` = "Lecturers",
                               `6` = "No Academic Rank",
                               .default = "Unassigned"),
         source = "instructors") %>%
  filter(facstat > 0,
         siscat %in% c(201, 202, 203, 204, 205, 206, 
                       301, 302, 303, 304, 305, 306, 
                       411, 412, 413, 414, 415, 416, 
                       421, 422, 423, 424, 425, 426,
                       431, 432, 433, 434, 435, 436,
                       500)) %>%
  select(unitid, source, occupcat, facstat, faculty_rank, time_status,
         hrnralm, hrnralw, hrunknm, hrunknw, hrhispm, hrhispw,
         hraianm, hraianw, hrasiam, hrasiaw, hrbkaam, hrbkaaw,
         hrnhpim, hrnhpiw, hrwhitm, hrwhitw, hr2morm, hr2morw)


```

# Inspect Contents

## Occupational Categories

```{r}
occupational_category
```

## Instructional Staff

```{r}
instructional_staff
```

## Fall Staff

```{r}
year <- params$year

fall_staff <- occupational_category %>%
  bind_rows(instructional_staff) %>%
  gather(hrnralm:hr2morw, key = "variable", value = "headcount") %>%
  separate(variable, c("survey", "demographic_key"), sep = c(2)) %>%
  mutate(date_key = (year * 10000) + 1101,
         occupational_category = recode(occupcat,
                                        `211` = "Instructional staff, primarily instruction",
                                        `212` = "Instructional staff, primarily instruction, exclusively credit",
                                        `213` = "Instructional staff, primarily instruction, exclusively not-for-credit",
                                        `214` = "Instructional staff, primarily instruction, combined credit/not-for-credit",
                                        `215` = "Instructional staff - Instruction/research/public service",
                                        `220` = "Research",
                                        `230` = "Public service",
                                        `250` = "Librarians, Curators, Archivists and other teaching Instructional support",
                                        `260` = "Librarians, Curators, and Archivists",
                                        `261` = "Archivists, Curators, and Museum Technicians",
                                        `262` = "Librarians",
                                        `263` = "Library Technicians",
                                        `264` = "Detailed library occupations not available for non-degree-granting institutions",
                                        `270` = "Other teaching and Instructional Support",
                                        `300` = "Management",
                                        `310` = "Business and Financial Operations",
                                        `320` = "Computer, Engineering, and Science",
                                        `330` = "Community Service, Legal, Arts, and Media",
                                        `340` = "Healthcare Practioners and Technical",
                                        `350` = "Service Occupations",
                                        `360` = "Sales and Related Occupations",
                                        `370` = "Office and Administrative Support",
                                        `380` = "Natural Resources, Construction, and Maintenance",
                                        `390` = "Production, Transportation, and Material Moving",
                                        `400` = "Graduate Assistants",
                                        `410` = "Graduate Assistants Teaching",
                                        `420` = "Graduate Assistants Research",
                                        `430` = "Graduate Assistants Management Occupations",
                                        `440` = "Graduate Assistants Business and Financial Operations Occupations",
                                        `450` = "Graduate Assistants Computer, Engineering, and Science Occupations",
                                        `460` = "Graduate Assistants Community Service, Legal, Arts, and Media",
                                        `470` = "Graduate Assistants Library and Instructional support",
                                        `480` = "Graduate Assistants Healthcare Practioners and Technical",
                                        .default = "Unknown"),
         # Use SIS Codes????
         contract_type_id = recode(facstat,
                                   `41` = 1, 
                                   `42` = 2,
                                   `43` = 3,
                                   .default = 0),
         contract_type = recode(facstat,
                                `41` = "Multi-year or Indefinite",
                                `42` = "Annual",
                                `43` = "Less-than-annual",
                                `44` = "Multi-year",
                                `45` = "Indefinite",
                                .default = "Unknown")) %>%
  select(unitid, date_key, source, occupcat, occupational_category, 
         facstat, faculty_rank, 
         contract_type_id, contract_type,
         time_status, demographic_key, headcount)

fall_staff
```

```{r}
write_db <- function(frame, db, tab) {
  con <- dbConnect(odbc::odbc(), db)
  
  answer <- system.time({ dbWriteTable(con,
                                       tab,
                                       frame,
                                       overwrite = TRUE
  ) })
  
  dbDisconnect(con)
  
  return(answer)
}


fall_staff %>%
  write_db("ched-staging", "ipeds_fall_staff")
```

