---
title: "R Notebook"
output: html_notebook
---

# Load Data From NCES

```{r}
# clear the workspace
rm(list=ls())

library(odbc)
library(tidyverse)

year <- 2014
archive <- c('f1314_f1a.zip','flags2014.zip')
infile <- c('f1314_f1a_rv.csv','flags2014.csv')

odbcString <- "cdw"
urlStub <- "http://nces.ed.gov/ipeds/datacenter/data/"

# access data via net
netLoad <- function(fileUrl, fileName)
{
  #Download data file
  temp <- tempfile()
  
  download.file(fileUrl,
                temp)
  
  data <- read_csv(unz(temp, fileName))
  
  unlink(temp)
  # rm(temp)
  
  names(data) <- tolower(names(data))
  return(data)
}

raw.dat <- netLoad(paste0(urlStub, archive[1]),
                    infile[1]) %>%
  left_join(netLoad(paste0(urlStub, archive[2]),
                    infile[2]), by = 'unitid') %>%
  mutate(Unitid = unitid,
         YearId = year)

raw.dat
```

# Restructure and Create Data Frame

```{r}

expenses <- raw.dat %>%
  gather(f1c012, f1c013, f1c014, f1c015, f1c016, f1c017,
         f1c022, f1c023, f1c024, f1c025, f1c026, f1c027,
         f1c032, f1c033, f1c034, f1c035, f1c036, f1c037,
         f1c052, f1c053, f1c054, f1c055, f1c056, f1c057,
         f1c062, f1c063, f1c064, f1c065, f1c066, f1c067,
         f1c072, f1c073, f1c074, f1c075, f1c076, f1c077,
         f1c082, f1c083, f1c084, f1c085, f1c086, f1c087,
         f1c105,
         f1c112, f1c113, f1c114, f1c115, f1c116, f1c117,
         f1c122, f1c123, f1c124, f1c125, f1c126, f1c127,
         f1c132, f1c133, f1c134, f1c135, f1c136, f1c137,
         f1c142, f1c143, f1c144, f1c145, f1c146, f1c147,
         key = 'field', value = 'Expense') %>%
  mutate(field = substr(field, 4, 6)) %>%
  separate(field, c('FunctionalClassification','NaturalClassification'), 2) %>%
  mutate(FunctionalClassification = recode(as.integer(FunctionalClassification),
                                             `1`='Instruction',
                                             `2`='Research',
                                             `3`='Public service',
                                             `5`='Academic support',
                                             `6`='Student services',
                                             `7`='Institutional support',
                                             `8`='Operation and maintenance of plant',
                                             `10`='Scholarships and fellowships',
                                             `11`='Auxiliary enterprises',
                                             `12`='Hospital services',
                                             `13`='Independent operations',
                                             `14`='Other',
                                             `15`='Total',
                                           .default='Class Fail'),
         NaturalClassification = recode(as.integer(NaturalClassification),
                                          `1`='Total',
                                          `2`='Salaries and wages',
                                          `3`='Fringe benefits',
                                          `4`='Depreciation',
                                          `5`='Other',
                                          `6`='Operation and maintenance of plant',
                                          `7`='Interest'),
         Expense = ifelse(is.na(Expense),0,Expense)) %>%
  select(Unitid,
         YearId,
         FunctionalClassification,
         NaturalClassification,
         Expense)

expenses
```

# Load Database

```{r}
con <- dbConnect(odbc::odbc(), odbcString)

response <- dbSendQuery(con, paste0('DELETE FROM dbo.IpedsExpenses WHERE YearId=', year))
dbClearResult(response)

system.time({ dbWriteTable(con, 'IpedsExpenses', expenses, append=TRUE) })

dbDisconnect(con)

```

