---
title: "R Notebook"
output: html_notebook
---

# Load Data From NCES

```{r}
# clear the workspace
rm(list=ls())

library(odbc)
library(tidyverse)

year <- 2016
archive <- c('f1516_f1a.zip','flags2016.zip')
infile <- c('f1516_f1a.csv','flags2016.csv')

odbcString <- "cdw"
urlStub <- "http://nces.ed.gov/ipeds/datacenter/data/"

# access data via net
netLoad <- function(fileUrl, fileName)
{
  #Download data file
  temp <- tempfile()
  
  download.file(fileUrl,
                temp)
  
  data <- read_csv(unz(temp, fileName))
  
  unlink(temp)
  # rm(temp)
  
  names(data) <- tolower(names(data))
  return(data)
}

raw.dat <- netLoad(paste0(urlStub, archive[1]),
                    infile[1]) %>%
  left_join(netLoad(paste0(urlStub, archive[2]),
                    infile[2]), by = 'unitid') %>%
  mutate(Unitid = unitid,
         YearId = year)

raw.dat
```

# Restructure and Create Data Frame

```{r}

expenses <- raw.dat %>%
  mutate(f1c017 = f1c011 - f1c012,
         f1c027 = f1c021 - f1c022,
         f1c037 = f1c031 - f1c032,
         f1c057 = f1c051 - f1c052,
         f1c067 = f1c061 - f1c062,
         f1c077 = f1c071 - f1c072,
         # f1c087 = f1c081 - f1c082,
         f1c107 = f1c101,
         f1c117 = f1c111 - f1c112,
         f1c127 = f1c121 - f1c122,
         f1c137 = f1c131 - f1c132,
         f1c147 = f1c141 - f1c142) %>%
  gather(f1c012,f1c017,
         f1c022,f1c027,
         f1c032,f1c037,
         f1c052,f1c057,
         f1c062,f1c067,
         f1c072,f1c077,
         # f1c087,f1c082,
         f1c107,
         f1c112,f1c117,
         f1c122,f1c127,
         f1c132,f1c137,
         f1c142,f1c147,
         key = 'field', value = 'Expense') %>%
  mutate(field = substr(field, 4, 6)) %>%
  separate(field, c('FunctionalClassification','NaturalClassification'), 2) %>%
  mutate(FunctionalClassification = recode(as.integer(FunctionalClassification),
                                             `1`='Instruction',
                                             `2`='Research',
                                             `3`='Public service',
                                             `5`='Academic support',
                                             `6`='Student services',
                                             `7`='Institutional support',
                                             `8`='Operation and maintenance of plant',
                                             `10`='Scholarships and fellowships',
                                             `11`='Auxiliary enterprises',
                                             `12`='Hospital services',
                                             `13`='Independent operations',
                                             `14`='Other',
                                             `15`='Total'),
         NaturalClassification = recode(as.integer(NaturalClassification),
                                          `1`='Total',
                                          `2`='Salaries and wages',
                                          `3`='Fringe benefits',
                                          `4`='Depreciation',
                                          `5`='Other',
                                          `6`='Operation and maintenance of plant',
                                          `7`='Interest'),
         Expense = ifelse(is.na(Expense),0,Expense)) %>%
  select(Unitid,
         YearId,
         FunctionalClassification,
         NaturalClassification,
         Expense)

expenses
```

# Load Database

```{r}
con <- dbConnect(odbc::odbc(), odbcString)

response <- dbSendQuery(con, paste0('DELETE FROM dbo.GasbExpenses WHERE YearId=', year))
dbClearResult(response)

system.time({ dbWriteTable(con, 'GasbExpenses', expenses, append=TRUE) })

dbDisconnect(con)

```

