---
title: "Load Geographic Entities"
author: "Jason P. Casey"
date: 2018-12-11
output: html_notebook
params:
  read_raw:
    label: "Read Raw"
    value: "Y"
---

# Setup

These will eventually be replaced by web-based data.  For now, they are fixed files and shouldn't need reloading.

```{r setup}
# knitr options
knitr::opts_chunk$set(fig.width = 8,
                      fig.asp = 0.618,
                      echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

# include user functions
source(file="../user-functions.R")

if (params$read_raw == "Y") {
  states <- read_csv("../../data/states.csv")
  
  cbsa <- read_csv("../../data/cbsa.csv")
  
  csa <- read_csv("../../data/csa.csv")
  
  counties <- read_csv("../../data/county.csv")
}

```

# Read Data

```{r}
if (params$read_raw == "N") {
  system.time({
    states <- read_db("ched-staging", "SELECT * FROM dbo.states")
    cbsa <- read_db("ched-staging", "SELECT * FROM dbo.cbsa")
    csa <- read_db("ched-staging", "SELECT * FROM dbo.csa")
    counties <- read_db("ched-staging", "SELECT * FROM dbo.counties")
    })
}

```

# Write Data

```{r}
system.time({
  cbsa %>%
    write_db("ched-staging", "cbsa")

  csa %>%
    write_db("ched-staging", "csa")

  counties %>%
    write_db("ched-staging", "counties")
  
  states %>%
    write_db("ched-staging", "states")
  
})
```

