---
title: "Load IPEDS Institutions"
author: "Jason P. Casey"
date: 2018-11-21
output: html_notebook
params:
  year:
    label: "Report Year:"
    value: 2017
---

```{r setup}
# knitr options
knitr::opts_chunk$set(fig.width = 8,
                      fig.asp = 0.618,
                      echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

# include user functions
library(DBI)
library(odbc)
library(readxl)
library(lubridate)
library(kableExtra)
library(tidyverse)

# access data via net
net_load <- function(file_url, file_name)
{
  #Download data file
  temp <- tempfile()
  
  download.file(file_url,
                temp)
  
  data <- read_csv(unz(temp, file_name),
                        locale = locale(encoding = "latin1")) %>%
    rename_all(tolower)
  
  unlink(temp)
  rm(temp)
  
  return(data)
}

read_db <- function(db, query_string)
{
  # Open a connection
  connection <- dbConnect(odbc::odbc(), db)
  
  response <- dbSendQuery(connection, query_string)
  tbl <- dbFetch(response)
  dbClearResult(response)
  
  # disconnect from the database
  dbDisconnect(connection)
  
  return(as_tibble(tbl))
}

write_db <- function(frame, db, tab, add = TRUE) {
  con <- dbConnect(odbc::odbc(), db)
  
  answer <- system.time({ dbWriteTable(con,
                                       tab,
                                       frame,
                                       overwrite=!add,
                                       append = add
                                       ) })
  
  dbDisconnect(con)
  
  return(answer)
}

read_aaude_data <- function(dbString, queryString)
{
  # Open a connection
  connection <- dbConnect(odbc::odbc(),
                          dbString, 
                          UID=rstudioapi::showPrompt('User ID','Enter User ID'),
                          PWD=rstudioapi::askForPassword("Database Password"))
  
  tbl <- dbReadTable(connection, tab) %>%
    rename_all(tolower)
  
  # dbClearResult(response)
  
  # disconnect from the database
  dbDisconnect(connection)
  
  return(as_tibble(tbl))
}

mo_yr <- function(date_string) {
  my_month <- str_extract(date_string, "^\\d{2}")
  my_year <- str_extract(date_string, "\\d{4}$")
  
  my_date <- lubridate::make_date(my_year, my_month, 1)
  
  #day(my_date) <- days_in_month(my_date)
  
  #my_day <- str_pad(days_in_month(my_date), 2, pad = "0")
  
  answer <- str_c(my_month,
        "/",
        str_pad(days_in_month(my_date), 2, pad = "0"),
        "/",
        my_year)
  
  return(answer)
}

fix_binary <- function(x) {
  recode(x,
         `1` = 1,
         `2` = 0)
}




# load dependencies
states <- read_db("cdw", "SELECT * FROM states")
institution_names <- read_excel("../../data/institution-names.xlsx")
nsf_institutions <- read_db("cdw", "SELECT unitid, med_sch_flag FROM nsf_herd_institution_data") %>%
  group_by(unitid) %>%
  summarize(med_sch_flag = max(med_sch_flag))

regents <- c(181464, 153658, 153603, 126614,
             126818, 145637, 155317, 174066,
             178396, 204796, 243780)

read_files <- function(spec1, spec2) {
  details <- read_csv(spec2,
                      locale = locale(encoding = "latin1")) %>%
    rename_all(tolower)
  
  recordset <- read_csv(spec1,
                        locale = locale(encoding = "latin1")) %>%
    rename_all(tolower) %>%
    rename(institution_name = instnm,
           state_abbreviation = stabbr,
           address = addr,
           web_address = webaddr) %>%
    left_join(details, by = "unitid") %>%
    left_join(nsf_institutions, by = "unitid") %>%
    mutate(unitid = as.integer(unitid),
           regents_peer = ifelse(unitid %in% regents, 1, 0),
           zip = as.character(zip),
           fips = as.integer(fips),
           service_academy = ifelse(as.integer(obereg) == 0, 1, 0),
           closedat = ifelse(is.na(closedat), "", closedat),
           closedat = ifelse(str_length(closedat) < 3, "", closedat),
           closedat = ifelse(str_detect(closedat, "^\\d{2}/\\d{4}$"),
                             mo_yr(closedat),
                             closedat),
           close_date = mdy(closedat),
           institution_level = recode(as.integer(iclevel),
                                      `1` = "Four or more years",
                                      `2` = "At least 2 but less than 4 years",
                                      `3` = "Less than 2 years (below associate)",
                                      .default = "Unknown"),
           control = recode(as.integer(control),
                            `1` = "Public",
                            `2` = "Private not-for-profit",
                            `3` = "Private for-profit",
                            .default = "Unknown"),
           highest_level_offering = recode(as.integer(hloffer),
                                           `1` = "Award of less than one academic year",
                                           `2` = "At least 1, but less than 2 academic yrs",
                                           `3` = "Associate's degree",
                                           `4` = "At least 2, but less than 4 academic yrs",
                                           `5` = "Bachelor's degree",
                                           `6` = "Postbaccalaureate certificate",
                                           `7` = "Master's degree",
                                           `8` = "Post-master's certificate",
                                           `9` = "Doctor's degree",
                                           .default = "Unknown"),
           highest_degree_offering = recode(as.integer(hdegofr1),
                                            `11` = "Doctor's degree - research/scholarship and professional practice",
                                            `12` = "Doctor's degree - research/scholarship",
                                            `13` = "Doctor's degree -  professional practice",
                                            `14` = "Doctor's degree - other",
                                            `20` = "Master's degree",
                                            `30` = "Bachelor's degree",
                                            `40` = "Associate's degree",
                                            `0` = "Non-degree granting",
                                            .default = "Unknown"),
           locale = recode(as.integer(locale),
                           `11` = "City: Large",
                           `12` = "City: Midsize",
                           `13` = "City: Small",
                           `21` = "Suburb: Large",
                           `22` = "Suburb: Midsize",
                           `23` = "Suburb: Small",
                           `31` = "Town: Fringe",
                           `32` = "Town: Distant",
                           `33` = "Town: Remote",
                           `41` = "Rural: Fringe",
                           `42` = "Rural: Distant",
                           `43` = "Rural: Remote",
                           .default = "Unknown"),
           parent_id = ifelse(newid > 0, newid, unitid),
           year_closed = ifelse(as.integer(deathyr) > 0, as.integer(deathyr), NA),
           cbsa_id = as.integer(cbsa),
           cbsa_type = recode(as.integer(cbsatype),
                              `1` = "Metropolitan Statistical Area",
                              `2` = "Micropolitan Statistical Area",
                              .default = "No CBSA"),
           csa_id = as.integer(csa),
           county_fips = as.integer(countycd),
           longitude = as.numeric(longitud),
           latitude = as.numeric(latitude),
           system_member = fix_binary(as.integer(f1systyp)),
           system_name = ifelse(str_trim(as.character(f1sysnam)) %in% c("-1", "-2", "-3"),
                                NA, as.character(f1sysnam)),
           undergraduate_offering = fix_binary(as.integer(ugoffer)),
           graduate_offering = fix_binary(as.integer(groffer)),
           degree_granting = fix_binary(as.integer(deggrant)),
           open_to_public = ifelse(as.integer(openpubl)==1, 1, 0),
           landgrant = fix_binary(as.integer(landgrnt)),
           hbcu = fix_binary(as.integer(hbcu)),
           hospital = fix_binary(as.integer(hospital)),
           medical = fix_binary(as.integer(medical)),
           nsf_medical_school = ifelse(as.integer(med_sch_flag)==1, 1, 0),
           tribal = fix_binary(as.integer(tribal)),
           postsecondary_institution = recode(as.integer(postsec),
                                              `1` = "Primarily postsecondary institution",
                                              `2` = "Not primarily postsecondary",
                                              `3` = "Not postsecondary",
                                              .default = "Unknown"),
           rotc = recode(as.integer(slo5),
                         `1` = 1,
                         `0` = 0),
           confno1 = as.integer(confno1),
           confno2 = as.integer(confno2),
           confno3 = as.integer(confno3),
           confno4 = as.integer(confno4),
           active = ifelse(as.integer(cyactive)==1, 1, 0)) %>%
    select(unitid, institution_name, address, city, zip,
           web_address, fips, county_fips, service_academy,
           institution_level, control, highest_level_offering, highest_degree_offering,
           undergraduate_offering, graduate_offering, degree_granting, 
           regents_peer, locale, parent_id, year_closed, close_date,
           cbsa_id, cbsa_type, csa_id, longitude, latitude,
           system_member, system_name, open_to_public, landgrant,
           hbcu, hospital, medical, nsf_medical_school, tribal, rotc,
           confno1, confno2, confno3, confno4
           )
}


```

# Read Data

```{r}
ic_meta <- tibble(year = 2010:2017)

for (i in seq_along(ic_meta$year)) {
  ic_meta <-
    ic_meta %>%
    mutate(directory_file = str_c("../../data/ic/hd", year, ".csv"),
           characteristics_file = ifelse(year == params$year,
                                         str_c("../../data/ic/ic", year, ".csv"),
                                         str_c("../../data/ic/ic", year, "_rv.csv")),
           data = map2(directory_file, characteristics_file, read_files)
           )
}

ic_meta

```

# Merge Data

```{r}
institutions <- ic_meta %>%
  #rename("year_id" = "year") %>%
  # mutate(year_id = year + 1) %>%
  select(year, data) %>%
  unnest() %>%
  mutate(year_id = year + 1) %>%
  select(year_id, everything(), -year)

institutions
```

# Write to Database

```{r}
system.time({
  con <- dbConnect(odbc::odbc(), "cdw")

  institutions %>%
    #select(-f1sysnam) %>%
    dbWriteTable(con,
                 "ipeds_institutions",
                 .,
                 overwrite = TRUE)

  dbDisconnect(con)
  
  institutions %>%
    write_csv("../../data/ic/insts.csv")
  })
```

# Find Unique Universe

```{r}
unique <- institutions %>%
  group_by(unitid) %>%
  summarize(year_id = max(year_id)) %>%
  ungroup() %>%
  inner_join(institutions) # %>%
  # select(-YearId)

table(unique$degree_granting)
```

# Find Systems

```{r}
unique %>%
  filter(!is.na(system_name)) %>%
  count(system_name) %>%
  arrange(desc(n), system_name)
```

# Test Net Load

```{r}
test <- net_load("https://nces.ed.gov/ipeds/datacenter/data/HD2017.zip", "hd2017.csv")

test
```

# Make States Table

```{r}
# system.time({
#   institutions %>%
#   count(fips, state_abbreviation, state, region) %>%
#   select(-n) %>%
#   write_db("cdw", "states", add = FALSE)
# })
states
```

# Create Place Codes

```{r}
cbsa <- read_excel("../../data/place_codes.xlsx",
                   sheet = "CBSA")

csa <- read_excel("../../data/place_codes.xlsx",
                   sheet = "CSA")

county <- read_excel("../../data/place_codes.xlsx",
                   sheet = "COUNTY") %>%
  count(county_fips, county_name, state) %>%
  select(-n)

county
```

```{r}
county %>%
  count(county_fips) %>%
  filter(n > 1) %>%
  inner_join(county)
```

```{r}
system.time({
  cbsa %>%
    write_db("cdw", "cbsa", add = FALSE)

  csa %>%
    write_db("cdw", "csa", add = FALSE)

  county %>%
    write_db("cdw", "counties", add = FALSE)
  
})
```

# Read AAU Membership

```{r}
aaude_inst <- grabData('aaude', "SELECT * FROM WAREUSER.INSTITUTION") %>%
  select(-warehouse_load_date)

aaude_inst
```

# Write AAU Membership Table

```{r}
system.time({
  institutions %>%
    filter(is_aau_institution == "Y") %>%
    select(unitid = unit_id,
           inst_name) %>%
    write_db("cdw", "aau_membership", add = FALSE)
})


```

