---
title: "Research and Development Analyses"
author: "Jason P. Casey"
date: 2018-11-20
output: html_document
---

```{r setup, include=FALSE}
# knitr options
knitr::opts_chunk$set(fig.width = 8,
                      fig.asp = 0.618,
                      echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)

library(DBI)
library(odbc)
library(kableExtra)
library(tidyverse)

set.seed(1965)

read_db <- function(db, query_string)
{
  # Open a connection
  connection <- dbConnect(odbc::odbc(), db)
  
  response <- dbSendQuery(connection, query_string)
  tbl <- dbFetch(response)
  dbClearResult(response)
  
  # disconnect from the database
  dbDisconnect(connection)
  
  return(as_tibble(tbl))
}

write_db <- function(frame, db, tab, add = TRUE) {
  con <- dbConnect(odbc::odbc(), db)
  
  answer <- system.time({ dbWriteTable(con,
                                       tab,
                                       frame,
                                       overwrite=!add,
                                       append = add) })
  
  dbDisconnect(con)
  
  return(answer)
}

institutions <- read_db("cdw", "SELECT * FROM dbo.NsfRdInstitutions")
rd <- read_db("cdw", "SELECT * FROM dbo.NsfRdByField")

```

## Do Something


```{r part1}
options(knitr.kable.NA = '')

institutions %>%
  inner_join(rd) %>%
  filter(State=="NE",
         `Highest Degree Granted` == "Doctorate") %>%
  group_by(RdFice, `Institution Name`, City, State, `Medical School`, `Type of Control`) %>%
  summarize(`Research Expenditures` = sum(Expenditure, na.rm = TRUE)) %>%
  ungroup %>%
  select(RdFice, `Institution Name`, City, State,
         `Medical School`, `Type of Control`, `Research Expenditures`) %>%
  arrange(desc(`Research Expenditures`)) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                font_size = 12) %>%
  row_spec(1,
           bold = TRUE,
           color = "white",
           background = "#D7261E")

```

## Plot Something


```{r plot1, echo=FALSE}
institutions %>%
  inner_join(rd) %>%
  filter(RdFice==2565,
         FundingType == "Federal") %>%
  group_by(FYear, BroadAcademicField) %>%
  summarize(`Research Expenditures` = sum(Expenditure, na.rm = TRUE)) %>%
  ungroup %>%
  ggplot(aes(x = FYear, y = `Research Expenditures`, color = BroadAcademicField)) +
    geom_line() +
    labs(x = "Fiscal Year",
         y = "Total Research Expenditures",
         color = "Academic Field",
         title = "Federal Funding by Academic Field",
         subtitle = "2010 - 2015")
```

